# Definir tipo de aplicacion
FROM node

# Direccion del proyecto/imagen y el nombre
WORKDIR /Belga

# Copiar el package.json desde el servidor al contenedor
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el proyecto al contenedor
COPY . .

# Puerto donde se va a levantar el contenedor (8080)
EXPOSE 8080

# Comando para correr la aplicacion
CMD ["npm", "start"]